# Generated by Django 3.1.2 on 2021-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintanence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_maintanence', models.BooleanField()),
                ('middle_ware_class', models.CharField(max_length=50)),
                ('middle_ware_app', models.CharField(max_length=50)),
            ],
        ),
    ]
